other branch

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -33,27 +33,32 @@ jobs:
           pyinstaller --onefile --name=agent.exe agent/__main__.py || pyinstaller --onefile --name=agent agent/__main__.py
           pyinstaller --onefile --name=bot.exe bot/__main__.py || pyinstaller --onefile --name=bot bot/__main__.py
 
-      - name: Archive built files
-        run: |
+          - name: Create Archives
+          run: |
             mkdir release
             cd dist
+            # Проверим, что файл создан
+            echo "Listing files in dist/ directory:"
+            ls -l
+        
+            # На Windows
             if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
-            powershell Compress-Archive -Path agent.exe -DestinationPath ../release/agent-windows-v${{ env.VERSION }}.zip
-            powershell Compress-Archive -Path bot.exe -DestinationPath ../release/bot-windows-v${{ env.VERSION }}.zip
+              powershell Compress-Archive -Path agent.exe -DestinationPath ../release/agent-windows-v${{ env.VERSION }}.zip
+              powershell Compress-Archive -Path bot.exe -DestinationPath ../release/bot-windows-v${{ env.VERSION }}.zip
             else
-            # На Linux проверяем, что файл существует перед упаковкой
-            if [ -f "agent" ]; then
-                zip -r ../release/agent-linux-v${{ env.VERSION }}.zip agent
-            else
-                echo "Error: agent file not found!"
-                exit 1
-            fi
-
-            if [ -f "bot" ]; then
-                zip -r ../release/bot-linux-v${{ env.VERSION }}.zip bot
-            else
-                echo "Error: bot file not found!"
-                exit 1
-            fi
+              # На Linux проверяем, что файл существует перед упаковкой
+              if [ -f "agent" ]; then
+                  zip -r ../release/agent-linux-v${{ env.VERSION }}.zip agent
+              else
+                  echo "Error: agent file not found!"
+                  exit 1
+              fi
+              
+              if [ -f "bot" ]; then
+                  zip -r ../release/bot-linux-v${{ env.VERSION }}.zip bot
+              else
+                  echo "Error: bot file not found!"
+                  exit 1
+              fi
             fi
             cd ..
