other branch

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -3,17 +3,17 @@ name: CI Pipeline
 on:
   push:
     branches:
-      - main  # Запускать на пуш в main
+      - main
   pull_request:
     branches:
-      - main  # Запускать при создании Pull Request в main
+      - main
 
 jobs:
   build:
-    runs-on: ${{ matrix.os }}  # Параллельная сборка для Windows и Linux
+    runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [windows-latest, ubuntu-latest]  # Параллельная сборка для Windows и Linux
+        os: [windows-latest, ubuntu-latest]
 
     steps:
       - name: Checkout code
@@ -27,144 +27,70 @@ jobs:
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install pyinstaller
-          pip install bump2version
           pip install -r requirements.txt
 
-      - name: Install fpm
+      - name: Install fpm (Linux only)
         if: runner.os == 'Linux'
         run: |
           sudo apt-get update
-          sudo apt-get install ruby-dev  # Устанавливаем зависимости для fpm
-          sudo gem install --no-document fpm  # Устанавливаем fpm
-          echo "fpm installed"
+          sudo apt-get install ruby-dev -y
+          sudo gem install --no-document fpm
 
-      - name: Set version environment variable for win
-        if: runner.os == 'Windows'  # Условие для Windows
-        run: |
-          $version = (Select-String -Pattern '(?<=version = ")[^"]*' pyproject.toml).Matches.Groups[0].Value
-          echo "VERSION=$version" >> $Env:GITHUB_ENV
-          echo "Version set to: $version"
+      - name: Install NSIS (Windows only)
+        if: runner.os == 'Windows'
+        run: choco install nsis -y
 
-      - name: Set version environment variable for linux
-        if: runner.os == 'Linux'  # Условие для Linux
+      - name: Set version environment variable
         run: |
-          VERSION=$(grep -Po '(?<=version = ")[^"]*' pyproject.toml)
-          echo "VERSION=${VERSION}" >> $GITHUB_ENV
-          echo "Version set to: $VERSION"
+          if [ "$RUNNER_OS" == "Windows" ]; then
+            $version = (Select-String -Path pyproject.toml -Pattern '(?<=version = \")[^\"]*').Matches.Groups[0].Value
+            if (!$version) { Write-Error "Version not found!"; exit 1 }
+            echo "VERSION=$version" >> $Env:GITHUB_ENV
+          else
+            VERSION=$(grep -Po '(?<=version = \")[^\"]*' pyproject.toml)
+            if [ -z "$VERSION" ]; then echo "Version not found!"; exit 1; fi
+            echo "VERSION=$VERSION" >> $GITHUB_ENV
+          fi
+
+      - name: Build executables
+        run: |
+          pyinstaller --onefile --name=agent agent/__main__.py
+          pyinstaller --onefile --name=bot bot/__main__.py
 
       - name: Build and package for Windows
-        if: runner.os == 'Windows'  # Условие для Windows
+        if: runner.os == 'Windows'
         run: |
-            # Создание .exe файлов с помощью PyInstaller
-            pyinstaller --onefile --name=agent.exe agent/__main__.py
-            pyinstaller --onefile --name=bot.exe bot/__main__.py
-  
-            # Проверка версии
-            echo version $env:VERSION !!!
-  
-            # Копируем .nsi файлы
-            echo "!include 'MUI2.nsh'" > agent_installer.nsi
-            echo "Outfile 'installer-agent-windows-v$env:VERSION.exe'" >> agent_installer.nsi
-            echo "InstallDir \$TEMP" >> agent_installer.nsi
-            cat agent_installer.nsi >> agent_installer.nsi
-            cat ./agent_installer.nsi >> agent_installer.nsi
-  
-            # Сборка установщика с помощью NSIS
-            if (Test-Path "C:\\Program Files (x86)\\NSIS\\makensis.exe") {
-              & "C:\\Program Files (x86)\\NSIS\\makensis.exe" agent_installer.nsi
-              & "C:\\Program Files (x86)\\NSIS\\makensis.exe" bot_installer.nsi
-            } else {
-              Write-Host "Error: NSIS not installed."
-              exit 1
-            }
+          mkdir release
+          & "C:\\Program Files (x86)\\NSIS\\makensis.exe" ./installer/agent_installer.nsi
+          & "C:\\Program Files (x86)\\NSIS\\makensis.exe" ./installer/bot_installer.nsi
 
-            # Проверим, существует ли файл, прежде чем перемещать
-            if (Test-Path "installer-agent-windows-v$env:VERSION.exe") {
-              Move-Item -Path "installer-agent-windows-v$env:VERSION.exe" -Destination "./release/"
-            } else {
-              Write-Host "Error: installer-agent-windows-v$env:VERSION.exe not found!"
-              exit 1
-            }
-  
-            if (Test-Path "installer-bot-windows-v$env:VERSION.exe") {
-              Move-Item -Path "installer-bot-windows-v$env:VERSION.exe" -Destination "./release/"
-            } else {
-              Write-Host "Error: installer-bot-windows-v$env:VERSION.exe not found!"
-              exit 1
-            }
-            
-            echo "Windows build and release complete."
-  
+          Move-Item -Path "installer-agent-windows-v${{ env.VERSION }}.exe" -Destination "./release/"
+          Move-Item -Path "installer-bot-windows-v${{ env.VERSION }}.exe" -Destination "./release/"
 
       - name: Build and package for Linux
-        if: runner.os == 'Linux'  # Условие для Linux
+        if: runner.os == 'Linux'
         run: |
-            echo "Starting the build process for Linux"
-        
-            pyinstaller --onefile --name=agent agent/__main__.py
-            pyinstaller --onefile --name=bot bot/__main__.py
-            
-            mkdir -p deb_pkg/opt/agent
-            mkdir -p deb_pkg/opt/bot
-        
-            if [ ! -f "dist/agent" ]; then
-              echo "Error: dist/agent not found!"
-              exit 1
-            else
-              echo "dist/agent exists"
-            fi
-        
-            echo "Checking if dist/bot exists"
-            if [ ! -f "dist/bot" ]; then
-              echo "Error: dist/bot not found!"
-              exit 1
-            else
-              echo "dist/bot exists"
-            fi
-        
-            cp dist/agent deb_pkg/opt/agent/    # Копируем бинарник агента
-            cp agent/config.json deb_pkg/opt/agent/  # Копируем конфигурационный файл агента
-        
-            echo "Copying files to deb_pkg/opt/bot/"
-            cp dist/bot deb_pkg/opt/bot/    # Копируем бинарник бота
-            cp bot/config.json deb_pkg/opt/bot/  # Копируем конфигурационный файл бота
-        
-            # Проверяем содержимое директории перед упаковкой
-            echo "Listing contents of deb_pkg/opt/agent"
-            ls -R deb_pkg/opt/agent/
-        
-            echo "Listing contents of deb_pkg/opt/bot"
-            ls -R deb_pkg/opt/bot/
-        
-            echo "Adding systemd services"
-            # Добавляем systemd сервисы для Linux
-            mkdir -p deb_pkg/etc/systemd/system
-            cp ./etc/systemd/system/agent.service deb_pkg/etc/systemd/system/
-            cp ./etc/systemd/system/bot.service deb_pkg/etc/systemd/system/
-        
-            echo "Listing contents of deb_pkg"
-            ls -R deb_pkg/
-        
-            # Проверяем, что все файлы на месте
-            echo "Building the .deb packages using fpm"
-            fpm -s dir -t deb -n agent -v ${{ env.VERSION }} deb_pkg/opt/agent/ deb_pkg/etc/systemd/system/
-            fpm -s dir -t deb -n bot -v ${{ env.VERSION }} deb_pkg/opt/bot/ deb_pkg/etc/systemd/system/
+          mkdir -p deb_pkg/opt/agent deb_pkg/opt/bot
 
-            ls .
-        
-            # Перемещаем .deb файлы в release
-            echo "Moving .deb files to release"
-            echo "mkdir -p ./release"
-            mkdir -p ./release
-            mv agent_${{ env.VERSION }}_amd64.deb ./release/
-            mv bot_${{ env.VERSION }}_amd64.deb ./release/
-        
-            echo "Linux build and release complete."
+          cp dist/agent deb_pkg/opt/agent/
+          cp agent/config.json deb_pkg/opt/agent/
+          cp dist/bot deb_pkg/opt/bot/
+          cp bot/config.json deb_pkg/opt/bot/
+
+          mkdir -p deb_pkg/etc/systemd/system
+          cp ./etc/systemd/system/agent.service deb_pkg/etc/systemd/system/
+          cp ./etc/systemd/system/bot.service deb_pkg/etc/systemd/system/
+
+          fpm -s dir -t deb -n agent -v ${{ env.VERSION }} deb_pkg/opt/agent/ deb_pkg/etc/systemd/system/
+          fpm -s dir -t deb -n bot -v ${{ env.VERSION }} deb_pkg/opt/bot/ deb_pkg/etc/systemd/system/
+
+          mkdir -p release
+          mv agent_${{ env.VERSION }}_amd64.deb release/
+          mv bot_${{ env.VERSION }}_amd64.deb release/
 
   publish_release:
     runs-on: ubuntu-latest
-    needs: build  # Этот шаг будет выполнен только после успешных сборок для обеих платформ
+    needs: build
     if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
     steps:
       - name: Checkout code
@@ -172,21 +98,20 @@ jobs:
 
       - name: Bump version
         run: |
-          echo "Bumping version..."
           bump2version patch --allow-dirty
           git config user.name "github-actions"
           git config user.email "github-actions@github.com"
           git add pyproject.toml
           git commit -m "Bump version [skip ci]"
-          git tag v$(grep -Po '(?<=version = ")[^"]*' pyproject.toml)
+          git tag v$(grep -Po '(?<=version = \")[^\"]*' pyproject.toml)
           git push origin main --tags
 
       - name: Publish Release on GitHub
         uses: softprops/action-gh-release@v2
         with:
           files: |
-            release/installer-agent-windows-v$env:VERSION.exe
-            release/installer-bot-windows-v$env:VERSION.exe
+            release/installer-agent-windows-v${{ env.VERSION }}.exe
+            release/installer-bot-windows-v${{ env.VERSION }}.exe
             release/agent-${{ env.VERSION }}-1_amd64.deb
             release/bot-${{ env.VERSION }}-1_amd64.deb
         env:
