other branch

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -43,15 +43,17 @@ jobs:
       - name: Set version environment variable (Windows)
         if: runner.os == 'Windows'
         run: |
-          $version = (Select-String -Path pyproject.toml -Pattern '(?<=version = \")[^\"]*').Matches.Groups[0].Value
-          if (!$version) { Write-Error "Version not found!"; exit 1 }
-          echo "VERSION=$version" >> $Env:GITHUB_ENV
-
+          $base_version = (Select-String -Path pyproject.toml -Pattern '(?<=version = \")[^\"]*').Matches.Groups[0].Value
+          if (!$base_version) { Write-Error "Version not found!"; exit 1 }
+          $full_version = "$base_version.${env:GITHUB_RUN_NUMBER}"
+          echo "VERSION=$full_version" >> $Env:GITHUB_ENV
+      
       - name: Set version environment variable (Linux)
         if: runner.os == 'Linux'
         run: |
-          VERSION=$(grep -Po '(?<=version = \")[^\"]*' pyproject.toml)
-          if [ -z "$VERSION" ]; then echo "Version not found!"; exit 1; fi
+          base_version=$(grep -Po '(?<=version = \")[^\"]*' pyproject.toml)
+          if [ -z "$base_version" ]; then echo "Version not found!"; exit 1; fi
+          VERSION="${base_version}.${GITHUB_RUN_NUMBER}"
           echo "VERSION=$VERSION" >> $GITHUB_ENV
 
       - name: Build executables
@@ -109,7 +111,7 @@ jobs:
       - name: Download build artifacts
         uses: actions/download-artifact@v4
         with:
-          name: build-artifacts
+          name: build-artifacts-${{ matrix.os }}
           path: release
 
       - name: Bump version
